"""user estudiante cita tables

Revision ID: 460285157b80
Revises: 
Create Date: 2021-11-14 13:46:25.944798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460285157b80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiante',
    sa.Column('carne', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('carrera', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('carne')
    )
    op.create_index(op.f('ix_estudiante_carrera'), 'estudiante', ['carrera'], unique=False)
    op.create_index(op.f('ix_estudiante_nombre'), 'estudiante', ['nombre'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('carne', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carne'], ['estudiante.carne'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cita_hora'), 'cita', ['hora'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cita_hora'), table_name='cita')
    op.drop_table('cita')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_estudiante_nombre'), table_name='estudiante')
    op.drop_index(op.f('ix_estudiante_carrera'), table_name='estudiante')
    op.drop_table('estudiante')
    # ### end Alembic commands ###
