"""Appointment Table

Revision ID: 4904353f8b44
Revises: 9cde61e074f2
Create Date: 2021-10-21 15:38:26.220110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4904353f8b44'
down_revision = '9cde61e074f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.DateTime(), nullable=True),
    sa.Column('carne', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'carne')
    )
    op.create_index(op.f('ix_cita_hora'), 'cita', ['hora'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cita_hora'), table_name='cita')
    op.drop_table('cita')
    # ### end Alembic commands ###
